[package]
name = "qint"
version = "0.1.0"
authors = [ "Flakebi <flakebi@t-online.de>" ]
description = ""
edition = "2018"
build = "src/build.rs"

[build-dependencies]
tauri-build = { version = "1.0.0-beta.3" }

[features]
custom-protocol = [ "tauri/custom-protocol" ]
default = [ "custom-protocol" ]

[dependencies]
actix = "0.12"
actix-rt = "2"
anyhow = "1"
base64 = "0.13"
bytes = "1"
futures = "0.3"
juniper = "0.15"
proxy-codegen = { path = "../proxy-codegen" }
qint-proxy = { path = "../proxy" }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
slog-async = "2"
slog-envlogger = "2"
slog-scope = "4"
slog-stdlog = "4"
slog-term = "2"
structopt = { version = "0.3", default-features = false }
tauri = { version = "1.0.0-beta.5", features = ["api-all", "system-tray", "menu"] }
thiserror = "1"
tokio = "1"
tokio-util = { version = "0.6", features = [ "io" ] }
tsclientlib = { path = "../../tsclientlib/tsclientlib", features = [ "unstable" ] }
tsproto-types = { path = "../../tsclientlib/utils/tsproto-types" }
uuid = { version = "0.8", features = [ "serde" ] }

[dependencies.log]
version = "0.4"
features = [ "max_level_info", "release_max_level_info" ]

[dependencies.slog]
version = "2"
features = [ "max_level_trace", "release_max_level_debug" ]

[target."cfg(windows)".build-dependencies]
winres = "0.1"
