[workspace]
members = ["proxy-codegen", "proxy", "src-tauri", "webapp"]
resolver = "2"

[patch.crates-io]
# Use cmake to build opus instead of autoconf, this works better for cross compilation
audiopus = { git = "https://github.com/Flakebi/audiopus" }
# Fix windows cross-compilation
crunchy = { git = "https://github.com/Flakebi/crunchy" }
# Fix modifying src directory
tauri-plugin = { git = "https://github.com/Flakebi/tauri-plugin" }

# Use local copy of tsclientlib
#[patch."https://github.com/ReSpeak/tsclientlib"]
#tsclientlib = { path = "../tsclientlib/tsclientlib" }
#tsproto = { path = "../tsclientlib/tsproto" }
#ts-bookkeeping = { path = "../tsclientlib/utils/ts-bookkeeping" }
#tsproto-packets = { path = "../tsclientlib/utils/tsproto-packets" }
#tsproto-structs = { path = "../tsclientlib/utils/tsproto-structs" }
#tsproto-types = { path = "../tsclientlib/utils/tsproto-types" }

# Compile in release mode to speed up
[profile.dev.package.audiopus]
opt-level = 3
[profile.dev.package.ebur128]
opt-level = 3
[profile.dev.package.nnnoiseless]
opt-level = 3

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
