[workspace]
members = ["proxy-codegen", "proxy", "src-tauri", "webapp"]
resolver = "2"

[patch.crates-io]
# Alternative branch uses cmake instead of autoconf, which works better for cross compilation
audiopus = { git = "https://github.com/DoumanAsh/audiopus", branch = "better_sys" }
opusic-sys = { git = "https://github.com/Flakebi/opusic-sys" }
webview2-com-sys = { git = "https://github.com/Flakebi/webview2-rs" }

# Use local copy of tsclientlib
#[patch."https://github.com/ReSpeak/tsclientlib"]
#tsclientlib = { path = "../tsclientlib/tsclientlib" }
#tsproto = { path = "../tsclientlib/tsproto" }
#ts-bookkeeping = { path = "../tsclientlib/utils/ts-bookkeeping" }
#tsproto-packets = { path = "../tsclientlib/utils/tsproto-packets" }
#tsproto-structs = { path = "../tsclientlib/utils/tsproto-structs" }
#tsproto-types = { path = "../tsclientlib/utils/tsproto-types" }

# Compile in release mode to speed up
[profile.dev.package.audiopus]
opt-level = 3
[profile.dev.package.ebur128]
opt-level = 3
[profile.dev.package.nnnoiseless]
opt-level = 3

[profile.release]
debug = true
panic = "abort"

[profile.dev]
panic = "abort"
