[workspace]
members = ["proxy-codegen", "proxy", "src-tauri"]
resolver = "2"

[patch.crates-io]
# Alternative branch uses cmake instead of autoconf, which works better for cross compilation
audiopus = { git = "https://github.com/DoumanAsh/audiopus", rev = "775541995a33060dcf060cc71bacaaa033e72561" }
opusic-sys = { git = "https://github.com/Flakebi/opusic-sys" }

# Compile in release mode to speed up
[profile.dev.package.audiopus]
opt-level = 3
[profile.dev.package.ebur128]
opt-level = 3
[profile.dev.package.nnnoiseless]
opt-level = 3

[profile.release]
debug = true
panic = "abort"

[profile.dev]
panic = "abort"
