[package]
name = "proxy-codegen"
version = "0.1.0"
authors = ["Flakebi <flakebi@t-online.de>"]
edition = "2018"
build = "build/build.rs"

[dependencies]
anyhow = "1"
fancy-regex = "0.10"
lazy_static = "1"
nom = "7.0.0-alpha2"
pulldown-cmark = "0.9"
serde = { version = "1", features = [ "derive" ] }
time = "0.3"
tsclientlib = { git = "https://github.com/ReSpeak/tsclientlib", features = [ "unstable" ] }
tsproto = { git = "https://github.com/ReSpeak/tsclientlib" }
tsproto-packets = { git = "https://github.com/ReSpeak/tsclientlib" }
tsproto-types = { git = "https://github.com/ReSpeak/tsclientlib" }
url = "2"

[build-dependencies]
heck = "0.4"
t4rust-derive = "0.3"
tsproto-structs = { git = "https://github.com/ReSpeak/tsclientlib", version = "0.2" }
