[package]
name = "qint-proxy"
version = "0.1.0"
authors = [ "Flakebi <flakebi@t-online.de>" ]
edition = "2018"
build = "build/build.rs"
description = "Qint is a TeamSpeak client"

[dependencies]
actix = "0.10"
actix-cors = "0.5"
actix-files = "0.4"
actix-web = "3"
actix-web-actors = "3"
actix-rt = "1"
anyhow = "1"
audiopus = "0.2"
base64 = "0.13"
chrono = { version = "0.4", features = [ "serde" ] }
diesel = { version = "1.4", features = [ "chrono", "sqlite" ] }
diesel-derive-enum = { version = "1", features = [ "sqlite" ] }
diesel_migrations = "1.4"
directories = "3"
ebur128 = "0.1"
fancy-regex = "0.4"
flakebi-ring = "0.16.9"
futures = "0.3"
git-testament = "0.1"
juniper = { git = "https://github.com/graphql-rust/juniper" }
lazy_static = "1"
libsqlite3-sys = { version = "0.18", features = [ "bundled" ] }
livesplit-hotkey = "0.5"
meilisearch-core = { git = "https://github.com/meilisearch/MeiliSearch", version = "0.16.0" }
nnnoiseless = "0.3"
nom = "6"
open = "1"
percent-encoding = "2.1"
pulldown-cmark = "0.8"
regex = "1"
reqwest = "0.10"
rmp-serde = "0.14"
scraper = "0.12"
sdl2 = "0.34"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
slog-async = "2"
slog-envlogger = "2"
slog-scope = "4"
slog-stdlog = "4"
slog-term = "2"
structopt = { version = "0.3", default-features = false }
tauri = { version = "0.9", features = [ "all-api" ] }
time = "0.2"
toml = "0.5"
tokio = { version = "0.2", features = [ "fs" ] }
tokio-util = { version = "0.3", features = [ "codec" ] }
tsclientlib = { path = "../../tsclientlib/tsclientlib", features = [ "unstable" ] }
tsproto = { path = "../../tsclientlib/tsproto" }
tsproto-packets = { path = "../../tsclientlib/utils/tsproto-packets" }
tsproto-types = { path = "../../tsclientlib/utils/tsproto-types" }
url = "2"
uuid = { version = "0.8", features = [ "serde" ] }

[dependencies.log]
version = "0.4"
features = [ "max_level_info", "release_max_level_info" ]

[dependencies.slog]
version = "2"
features = [ "max_level_trace", "release_max_level_debug" ]

[build-dependencies]
heck = "0.3"
t4rust-derive = "0.3"
tsproto-structs = { path = "../../tsclientlib/utils/tsproto-structs", version = "=0.1.0" }

[dev-dependencies]
actix-codec = "0.3"
awc = "2"
rand = "0.7"
tempfile = "3"
uuid = { version = "0.8", features = [ "v4" ] }

[features]
embedded-server = [ "tauri/embedded-server" ]
no-server = [ "tauri/no-server" ]
