name: Build and Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: nixbuild/nix-quick-install-action@v34
      with:
        nix_conf: |
          keep-env-derivations = true
          keep-outputs = true

    # - name: Build frontend and replace hash
    #   run: |
    #     nix build .#node_modules -L 2>&1 | tee log
    #
    #     # Extract wanted hash from log
    #     nodeModulesHash="$(sed -n 's/^ *got: *\(sha256-.*\)$/\1/p' log)"
    #     echo Got hash "$nodeModulesHash"
    #
    #     # Replace hash in flake.nix
    #     sed -i "s#pkgs.lib.fakeHash#\"$nodeModulesHash\"#g" flake.nix

    # - name: Check
    #   run: |
    #     nix flake check -L

    - name: Build Linux
      run: |
        nix build

    - name: Build Windows
      run: |
        nix build .#win-tauri-package

    # - name: Setup Attic cache
    #   uses: ryanccn/attic-action@v0
    #   with:
    #     endpoint: ${{ vars.ATTIC_ENDPOINT }}
    #     cache: ${{ vars.ATTIC_CACHE }}
    #     token: ${{ secrets.ATTIC_TOKEN }}
    #     skip-push: true
    #
    # - name: Push Cache
    #   run: attic push respeak ./result
