name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  FRONTEND_PATH: './ui/'

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        path: Qint
    - uses: actions/checkout@v3
      with:
        repository: ReSpeak/tsclientlib
        submodules: true
        path: tsclientlib
    - name: Install deps
      run: |
        cd ./Qint
        version="2.26.2"
        sdlVC="./target/sdl.zip"
        sdlMinGW="./target/sdl.tar.gz"
        mkdir -p ./target/sdlVC
        mkdir -p ./target/sdlMinGW
        rm -f $sdlVC
        rm -f $sdlMinGW
        curl "https://www.libsdl.org/release/SDL2-devel-$version-VC.zip" -o $sdlVC
        curl "https://www.libsdl.org/release/SDL2-devel-$version-mingw.tar.gz" -o $sdlMinGW
        unzip -o $sdlVC -d ./target/sdlVC/
        tar -xf $sdlMinGW -C ./target/sdlMinGW/
        mkdir -p ./proxy-codegen/msvc/lib/64
        mkdir -p ./proxy-codegen/msvc/dll/64
        mkdir -p ./proxy-codegen/gnu-mingw/lib/64
        mkdir -p ./proxy-codegen/gnu-mingw/dll/64
        cp ./target/sdlVC/SDL2-$version/lib/x64/*.lib ./proxy-codegen/msvc/lib/64/
        cp ./target/sdlVC/SDL2-$version/lib/x64/*.dll ./proxy-codegen/msvc/dll/64/
        cp ./target/sdlMinGW/SDL2-$version/x86_64-w64-mingw32/lib/*.a ./proxy-codegen/gnu-mingw/lib/64/
        cp ./target/sdlMinGW/SDL2-$version/x86_64-w64-mingw32/bin/*.dll ./proxy-codegen/gnu-mingw/dll/64/
        cp ./target/sdlMinGW/SDL2-$version/x86_64-w64-mingw32/bin/*.dll ./proxy-codegen/
        rm -f $sdlVC
        rm -f $sdlMinGW
        rm -rf ./target/sdlVC
        rm -rf ./target/sdlMinGW
    - name: Build Backend
      run: |
        cd ./Qint/webapp
        RUSTFLAGS="-C link-args=-lssp -C link-args=-s" cargo build --release --target=x86_64-pc-windows-gnu
    - name: Build Frontend
      run: |
        cd ./Qint/frontend
        yarn
        yarn build
    - name: Package
      run: |
        cd ./Qint
        rm -rf ./target/publish
        mkdir -p ./target/publish/ui
        cp ./target/x86_64-pc-windows-gnu/release/webapp.exe ./target/publish/
        #cp ./target/x86_64-pc-windows-gnu/release/WebView2Loader.dll ./target/publish/
        cp ./proxy-codegen/SDL2.dll ./target/publish/
        cp /usr/lib/gcc/x86_64-w64-mingw32/10-win32/libssp-0.dll ./target/publish/
        cp -r ./frontend/dist/* ./target/publish/ui/
        cd ./target/publish/
        mv webapp.exe qint.exe
        zip ./Qint.zip ui qint.exe libssp-0.dll SDL2.dll -r -9
